### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by noveens** [noveens/js-owncloud-client#4]
TODOs : 
- [ ] Improve swagger response format
- [x] ```docs-swagger/server.js``` is full of repeated code
- [ ] Split the ownCloud class into seperate classes : https://github.com/owncloud/pyocclient/issues/67
- [x] Write tests
- [x] Return promises along with call-backs
- [x] JSDoc
- [x] Makefile
- [x] JSHint
- [x] README
- [ ] Some methods, could be re-used when returning objects like groups, users.
- [ ] Fix JSDoc for returning promises.
- [x] Fix tests for promises.

@PVince81 anymore?
